sudo: required
services:
    - docker

before_install:
    - docker build -t sshek007/docker-react -f Dockerfile.dev .

script:
    - docker run sshek007/docker-react npm run test -- --coverage

after_script:
    - exit

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-325868861790"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
    