sudo: required
services:
    - docker

before_install:
    - docker build -t shashis/docker-react -f Dockerfile.dev .

script:
    - docker run shashis/docker-react npm run test -- --coverage
    - YARN_GPG=no
    